### PR TITLE
Create react app with create-react-app

### PR DESCRIPTION
**Pull request by flemton**
# Dear reviewer:
##  It is a great pleasure to request review for my Pull Request before I merge into dev branch

Below were the changes implemented in the branch
- Followed GitFlow
- Linters had already been setup in a different branch and merged into dev before this
- Created a react app with `npx create-react-app` command
__Any suggested changes are most welcome, cheers 🥂__

### CODE REVIEW

**Review by Alfredbis29 — CHANGES_REQUESTED** [review]
### Hi @flemton ,
 You did a great job so far 👏🏼 👏🏼 There are some issues that you still need to work on to go to the next project but you are almost there!
 
 
 ### To highlight 💪🏻
Your project is professional :white_check_mark:
Your repo is okay :white_check_mark:
No Linter errors :white_check_mark: 
:+1:  Good job!

## STATUS: CHANGES REQUESTED 
[ ]You've done a great job so far on this project, but you still need to improve on something for it to be approved. I noticed that your in `README` file the  M.I.T License is not really working since you provide a wrong link ,please include it because using the MIT License in our projects as student at Microverse can provides us  with a number of benefits, including collaboration opportunities, improved skills, portfolio building, career opportunities, and networking., kindly make sure that your M.I.T license is working properly :wink: 
WrongMIT

 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Cheers and Happy coding! :clap: :clap: :clap: :computer: Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please ping me @alfredbis29 when you comment so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by flemton** [comment]
@Alfredbis29 Thank you very much for the great review, I will add that real quick, cheers 🥂.

**Review by cynthiainga — APPROVED** [review]
## STATUS APPROVED ✔️ ✔️ 

Hi @flemton, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

- [OPTIONAL] I think it would be better if you add more information in your README file like " the project title, project description, your contact info,..." 🙃 🙃 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by OyePriscilla — COMMENTED** [review]
Hi @flemton 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
App implemented with Create React App  in React 👍 
Application run in browser without errors 👍 

## Optional suggestions

- [optional] Kindly fix the broken link in the `Acknowledgement` section of your README file, this will make your repo to be more informative. 👍  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
