### PR TITLE
Add routing

### PR DESCRIPTION
**Pull request by flemton**
Dear reviewer, it is a pleasure to request a review for my branch before merging into main

Changes that were implemented in the branch are as follows:
- [Add react-router-dom to project dep](https://github.com/flemton/math-magicians/commit/9e790d5f1d091fa721aa1ca3addb0fb5d3d18e8a)
- [Add calculator page route](https://github.com/flemton/math-magicians/commit/fbec5e6df7f5547553419d1cd17c2b05567ae142)
- [Add not found route](https://github.com/flemton/math-magicians/commit/4a525b9f16ceba085532a9c4c533304dc61b8fc0)
- [Add layout and outlet components to route](https://github.com/flemton/math-magicians/commit/9a9261309d99a44a0dd7ec8b4b86163e4b8d78d9)
- [Add navbar links](https://github.com/flemton/math-magicians/commit/2173882065d5720fac9192dc09e63ba659f159ba)
- [Update and style home component](https://github.com/flemton/math-magicians/commit/9207227112af12c6eb7e6bae78cb803f6d8b3c0a)
- [Add quotes component](https://github.com/flemton/math-magicians/commit/d9b8f1509a8f540eb5d3ecf0d641933f60fe307d)
__Any corrections or suggested changes are welcome and will help in the long run, cheers 🥂__

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️

Hi @flemton , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Great job adding NotFound.js page
:heavy_check_mark: All 3 pages as per project requirements added
:heavy_check_mark: Use of React-Router

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Great job working on this milestone. The live link in your ReadMe file is broken and leads to an error 404 page. Live demo link is not a compulsory project requirements. As such if the link is not working, you use the text `Coming Soon ...`
Screen Shot 2023-02-21 at 6 55 57 PM


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by flemton** [comment]
Dear @t-yanick , thank you very much for the awesome review, will do that, cheers 👏.

**Review by t-yanick — APPROVED** [review]
Hi @flemton , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  ReadMe Template used and personalized 
:heavy_check_mark: No broken links 
:heavy_check_mark:  All linter checks passing 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Qoosim — COMMENTED** [review]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @flemton, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
